name: GHCup Setup
description: Download a pre-built version of GHCup and add it to the PATH
author: Andrea Bedini

branding:
  icon: download

inputs:
  version:
    description: GHCup version to install
    default: latest
  release-channels:
    description: Set the release-channels
    default: |
      GHCupURL

outputs:
  path:
    description: Path to the installed GHCup
  version:
    description: Version of the installed GHCup

runs:
  using: node20
  main: ghcup/dist/index.js
